import { trpc } from "@/lib/trpc";
import { CalendarDays, ExternalLink, Info } from "lucide-react";
import { getDeadlineUrgency } from "../../../server/trackerLogic";

const urgencyStyle = { red: "border-rose-200 bg-rose-50 text-rose-800", yellow: "border-amber-200 bg-amber-50 text-amber-800", green: "border-emerald-200 bg-emerald-50 text-emerald-800", past: "border-slate-200 bg-slate-50 text-slate-500", unknown: "border-violet-100 bg-violet-50 text-violet-800" };
export default function CalendarPage() {
  const { data: applications = [] } = trpc.tracker.applications.list.useQuery();
  const dated = applications.flatMap(item => item.deadlines.filter(deadline => deadline.deadlineDate).map(deadline => ({ ...deadline, program: item.program }))).sort((a, b) => new Date(a.deadlineDate!).getTime() - new Date(b.deadlineDate!).getTime());
  return <div className="content-frame page-enter space-y-6"><section className="surface p-6 sm:p-8"><p className="section-kicker">Deadline calendar</p><h1 className="font-editorial mt-2 text-4xl font-semibold tracking-tight text-slate-950">Know what needs attention next.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">Dates are shown only when a program record contains an official, current-cycle calendar date. Red is under 30 days, yellow is under 60 days, and green is more than 60 days away.</p><div className="mt-5 flex flex-wrap gap-2 text-xs font-bold"><span className="rounded-full bg-rose-100 px-3 py-1.5 text-rose-800">Under 30 days · red</span><span className="rounded-full bg-amber-100 px-3 py-1.5 text-amber-800">Under 60 days · yellow</span><span className="rounded-full bg-emerald-100 px-3 py-1.5 text-emerald-800">60+ days · green</span></div></section>{dated.length ? <section className="grid gap-3">{dated.map(item => { const urgency = getDeadlineUrgency(item.deadlineDate); return <a href={item.sourceUrl} target="_blank" rel="noreferrer" key={item.id} className={`interactive-card flex flex-col justify-between gap-3 rounded-2xl border p-5 sm:flex-row sm:items-center ${urgencyStyle[urgency]}`}><div><p className="font-mono-ui text-[.63rem] uppercase tracking-[.14em]">{item.program.degreeType === "phd" ? "PhD" : "Master’s"} · {item.applicantType}</p><h2 className="mt-1 font-bold">{item.program.universityName}</h2><p className="mt-1 text-sm opacity-80">{item.deadlineLabel ?? "Official deadline"}</p></div><div className="flex items-center gap-3"><span className="font-mono-ui text-sm font-bold">{new Date(`${item.deadlineDate}T00:00:00`).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" })}</span><ExternalLink className="h-4 w-4" /></div></a>; })}</section> : <section className="surface py-18 text-center"><CalendarDays className="mx-auto h-9 w-9 text-violet-400" /><h2 className="mt-4 text-xl font-bold">No current-cycle dated deadlines yet.</h2><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-slate-600">The initial verified records hold annual guidance or historical dates, which are intentionally excluded from urgency alerts until each institution publishes a current-cycle date.</p><div className="mx-auto mt-5 flex max-w-lg items-start gap-2 rounded-xl bg-violet-50 p-4 text-left text-xs leading-5 text-violet-900"><Info className="mt-0.5 h-4 w-4 shrink-0" />The calendar protects you from treating a prior year’s deadline as current. Open each program’s official deadline source when preparing an application.</div></section>}</div>;
}
