import { Link } from "wouter";
import { trpc } from "@/lib/trpc";
import { ArrowRight, CalendarClock, CheckCircle2, ClipboardList, Compass, FileCheck2, ShieldCheck } from "lucide-react";
import { orderNextActions } from "../../../shared/applicationPlanning";

const labels: Record<string, string> = { researching: "Researching", applied: "Applied", interview: "Interview", offer: "Offer", accepted: "Accepted", rejected: "Rejected" };

function dateValue(value: Date | string | null | undefined) { return value ? new Date(String(value)) : null; }
function displayDate(value: Date | string | null | undefined) { const date = dateValue(value); return date && !Number.isNaN(date.getTime()) ? date.toLocaleDateString(undefined, { month: "short", day: "numeric" }) : "Confirm date"; }

export default function Home() {
  const { data: applications = [] } = trpc.tracker.applications.list.useQuery();
  const { data: directory = [] } = trpc.tracker.directory.list.useQuery({}, { staleTime: 60_000 });
  const completedDocuments = applications.flatMap(item => item.documents).filter(document => document.isComplete).length;
  const totalDocuments = applications.flatMap(item => item.documents).length;
  const today = new Date();
  const next60 = new Date(today); next60.setDate(next60.getDate() + 60);
  const applicationDeadlines = applications.flatMap(item => item.deadlines.filter(deadline => deadline.deadlineDate).map(deadline => ({ ...deadline, program: item.program, application: item.application }))).filter(item => { const date = dateValue(item.deadlineDate); return date && date >= today; }).sort((a, b) => dateValue(a.deadlineDate)!.getTime() - dateValue(b.deadlineDate)!.getTime());
  const nearDeadlines = applicationDeadlines.filter(item => dateValue(item.deadlineDate)! <= next60);
  const actionQueue = orderNextActions(applications.map(item => ({ ...item, nextAction: item.application.nextAction }))).slice(0, 5);
  const counts = applications.reduce<Record<string, number>>((accumulator, item) => ({ ...accumulator, [item.application.status]: (accumulator[item.application.status] ?? 0) + 1 }), {});

  return <div className="content-frame page-enter space-y-5">
    <section className="surface overflow-hidden p-5 sm:p-7"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="section-kicker">Today</p><h1 className="font-editorial mt-2 text-4xl font-semibold tracking-tight text-slate-950 sm:text-5xl">Your application work, in order.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">A focused view of what is saved, what is due, and what needs your attention next. Program research stays separate from your personal decisions.</p></div><div className="flex flex-wrap gap-2"><Link href="/programs" className="inline-flex h-10 items-center gap-2 rounded-xl bg-violet-700 px-4 text-sm font-bold text-white transition hover:bg-violet-800 active:scale-95">Explore programs <Compass className="h-4 w-4" /></Link><Link href="/applications" className="inline-flex h-10 items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-sm font-bold text-slate-700 transition hover:border-violet-200 hover:text-violet-800 active:scale-95">My applications <ArrowRight className="h-4 w-4" /></Link></div></div></section>

    <section className="grid gap-3 md:grid-cols-3"><Metric icon={<ClipboardList className="h-5 w-5" />} label="Saved applications" value={applications.length.toString()} caption="Your active working list" color="violet" /><Metric icon={<CalendarClock className="h-5 w-5" />} label="Due within 60 days" value={nearDeadlines.length.toString()} caption="Dated official deadlines only" color="amber" /><Metric icon={<FileCheck2 className="h-5 w-5" />} label="Documents complete" value={`${completedDocuments}/${totalDocuments}`} caption="Across saved applications" color="teal" /></section>

    <section className="grid gap-5 xl:grid-cols-[1.08fr_.92fr]"><div className="surface p-5 sm:p-6"><div className="flex items-center justify-between gap-3"><div><p className="section-kicker">Next action queue</p><h2 className="mt-2 text-xl font-extrabold tracking-tight">Move the right application forward.</h2></div><Link href="/applications" className="text-sm font-bold text-violet-700 hover:text-violet-900">Open tracker</Link></div>{actionQueue.length ? <div className="mt-5 space-y-2">{actionQueue.map(item => { const nextDeadline = applicationDeadlines.find(deadline => deadline.program.id === item.program.id); return <Link key={item.application.id} href="/applications" className="group flex items-center justify-between gap-3 rounded-xl border border-slate-100 bg-slate-50/75 p-3.5 transition hover:border-violet-200 hover:bg-violet-50"><div className="min-w-0"><p className="truncate text-sm font-bold text-slate-900">{item.program.universityName}</p><p className="mt-1 truncate text-sm text-slate-600">{item.application.nextAction}</p></div><span className="shrink-0 rounded-lg bg-white px-2.5 py-1.5 font-mono-ui text-[0.65rem] font-bold text-slate-600">{nextDeadline ? displayDate(nextDeadline.deadlineDate) : "No date"}</span></Link>; })}</div> : <EmptyPanel icon={<ClipboardList className="h-5 w-5" />} text="Add a short next action to a saved application and it will appear here in deadline-aware order." action="Set an action" href="/applications" />}</div>
      <div className="surface p-5 sm:p-6"><div className="flex items-center justify-between gap-3"><div><p className="section-kicker">Upcoming deadlines</p><h2 className="mt-2 text-xl font-extrabold tracking-tight">Your dated official deadlines.</h2></div><Link href="/calendar" className="text-sm font-bold text-violet-700 hover:text-violet-900">Open calendar</Link></div>{applicationDeadlines.length ? <div className="mt-5 space-y-2">{applicationDeadlines.slice(0, 5).map(item => <Link key={item.id} href="/applications" className="group flex items-center justify-between gap-3 rounded-xl border border-slate-100 bg-slate-50/75 p-3.5 transition hover:border-amber-200 hover:bg-amber-50"><div className="min-w-0"><p className="truncate text-sm font-bold text-slate-900">{item.program.universityName}</p><p className="mt-1 truncate text-xs text-slate-600">{item.deadlineLabel ?? item.program.programName}</p></div><span className="shrink-0 rounded-lg bg-white px-2.5 py-1.5 font-mono-ui text-[0.65rem] font-bold text-amber-700">{displayDate(item.deadlineDate)}</span></Link>)}</div> : <EmptyPanel icon={<CalendarClock className="h-5 w-5" />} text="Saved programs with current dated official deadlines will appear here." action="Explore programs" href="/programs" />}</div></section>

    <section className="grid gap-5 xl:grid-cols-[.82fr_1.18fr]"><div className="surface p-5 sm:p-6"><p className="section-kicker">Application status</p><h2 className="mt-2 text-xl font-extrabold tracking-tight">Pipeline at a glance</h2><div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-3">{["researching", "applied", "interview", "offer", "accepted", "rejected"].map(status => <Link key={status} href="/applications" className="rounded-xl bg-slate-50 p-3 transition hover:bg-violet-50"><p className="text-xs font-semibold text-slate-600">{labels[status]}</p><p className="mt-1 text-2xl font-extrabold text-violet-700">{counts[status] ?? 0}</p></Link>)}</div></div><div className="surface p-5 sm:p-6"><p className="section-kicker">Evidence guardrails</p><h2 className="mt-2 text-xl font-extrabold tracking-tight">Useful information without invented facts.</h2><div className="mt-5 grid gap-3 sm:grid-cols-3"><Reason icon={<CheckCircle2 className="h-5 w-5" />} title="Admission-first" text="Fees, tests, deadlines, and funding appear before long program prose." /><Reason icon={<ShieldCheck className="h-5 w-5" />} title="Source-aware" text="GRE, Duolingo, and acceptance cues only appear where a record supports them." /><Reason icon={<Compass className="h-5 w-5" />} title="Separate goals" text={`${directory.length} public verified records stay distinct from your private application list.`} /></div></div></section>
  </div>;
}

function Metric({ icon, label, value, caption, color }: { icon: React.ReactNode; label: string; value: string; caption: string; color: "violet" | "teal" | "amber" }) { const colors = { violet: "bg-violet-50 text-violet-700", teal: "bg-teal-50 text-teal-700", amber: "bg-amber-50 text-amber-700" }; return <section className="surface p-5"><div className={`flex h-9 w-9 items-center justify-center rounded-xl ${colors[color]}`}>{icon}</div><p className="mt-4 text-3xl font-extrabold tracking-tight">{value}</p><p className="mt-1 text-sm font-bold text-slate-800">{label}</p><p className="mt-1 text-xs leading-5 text-slate-500">{caption}</p></section>; }
function EmptyPanel({ icon, text, action, href }: { icon: React.ReactNode; text: string; action: string; href: string }) { return <div className="mt-5 rounded-2xl border border-dashed border-slate-200 bg-slate-50/70 p-5 text-sm text-slate-600"><div className="text-violet-600">{icon}</div><p className="mt-3 max-w-md leading-6">{text}</p><Link href={href} className="mt-3 inline-flex items-center gap-1 font-bold text-violet-700 hover:text-violet-900">{action} <ArrowRight className="h-3.5 w-3.5" /></Link></div>; }
function Reason({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="rounded-2xl border border-slate-100 bg-slate-50 p-4"><div className="text-teal-600">{icon}</div><h3 className="mt-3 text-sm font-bold">{title}</h3><p className="mt-1 text-xs leading-5 text-slate-600">{text}</p></div>; }
