import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, BadgeCheck, BookmarkPlus, Building2, CheckCircle2, ExternalLink, FileText, Landmark, MapPin, ShieldCheck } from "lucide-react";
import { Link, useLocation, useRoute } from "wouter";
import { toast } from "sonner";

export default function ProgramDetails() {
  const [, params] = useRoute("/programs/:slug");
  const [, setLocation] = useLocation();
  const { data: program, isLoading } = trpc.tracker.directory.bySlug.useQuery({ slug: params?.slug ?? "" }, { enabled: Boolean(params?.slug) });
  const utils = trpc.useUtils();
  const add = trpc.tracker.applications.add.useMutation({ onSuccess: () => { utils.tracker.applications.list.invalidate(); toast.success("Added to My Applications"); }, onError: error => toast.error(error.message) });
  if (isLoading) return <div className="content-frame py-20 text-center text-slate-500">Loading verified record…</div>;
  if (!program) return <div className="content-frame py-20 text-center"><h1 className="font-editorial text-4xl">Program not found</h1><Link href="/programs" className="mt-4 inline-block font-bold text-violet-700">Return to directory</Link></div>;
  const degreeLabel = program.degreeType === "phd" ? "PhD" : "Master’s";
  const officialDeadline = program.deadlines.find(item => item.deadlineDate) ?? program.deadlines[0];
  const deadlineValue = officialDeadline?.deadlineDate ? new Date(String(officialDeadline.deadlineDate)).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" }) : officialDeadline?.deadlineLabel ?? null;
  const facts = [
    deadlineValue ? { label: "Deadline", value: deadlineValue, sourceUrl: officialDeadline?.sourceUrl, sourceLabel: "Official deadline" } : null,
    program.applicationFeeDisplay ? { label: "Application fee", value: program.applicationFeeDisplay, sourceUrl: program.admissionFactsSourceUrl, sourceLabel: program.admissionFactsSourceLabel } : null,
    program.grePolicy ? { label: "GRE", value: program.grePolicy, sourceUrl: program.admissionFactsSourceUrl, sourceLabel: program.admissionFactsSourceLabel } : null,
    program.duolingoPolicy ? { label: "Duolingo", value: program.duolingoPolicy, sourceUrl: program.admissionFactsSourceUrl, sourceLabel: program.admissionFactsSourceLabel } : null,
    program.englishTestPolicy ? { label: "English test", value: program.englishTestPolicy, sourceUrl: program.admissionFactsSourceUrl, sourceLabel: program.admissionFactsSourceLabel } : null,
    program.fundingStatus !== "not_stated" ? { label: "Funding", value: program.fundingStatus === "funded" ? "Funded" : program.fundingStatus === "available" ? "Funding available" : "Not applicable", sourceUrl: program.officialUrl, sourceLabel: "Official program source" } : null,
    program.acceptanceRate ? { label: "Acceptance rate", value: `${program.acceptanceRate}%`, sourceUrl: program.acceptanceRateSourceUrl, sourceLabel: program.acceptanceRateSourceLabel } : null,
  ].filter(Boolean) as Array<{ label: string; value: string; sourceUrl?: string | null; sourceLabel?: string | null }>;
  const requirements = program.applicationRequirements ?? [];

  return <div className="content-frame page-enter space-y-5">
    <button onClick={() => setLocation("/programs")} className="inline-flex items-center gap-2 text-sm font-bold text-slate-600 hover:text-violet-700"><ArrowLeft className="h-4 w-4" />Program explorer</button>
    <section className="surface overflow-hidden">
      <div className="relative h-72 overflow-hidden bg-[linear-gradient(120deg,#33206e,#7356ca_52%,#45b99a)] bg-cover bg-center sm:h-80" style={program.campusImageUrl ? { backgroundImage: `url(${program.campusImageUrl})` } : undefined}>
        <div className="absolute inset-0 bg-[linear-gradient(105deg,rgba(22,12,62,.88)_0%,rgba(34,24,78,.56)_48%,rgba(13,25,48,.2)_100%)]" />
        <div className="relative flex h-full flex-col justify-end p-6 text-white sm:p-8"><div className="mb-3 flex flex-wrap gap-2"><span className="rounded-full bg-white/18 px-3 py-1 font-mono-ui text-[0.65rem] uppercase tracking-[.15em] backdrop-blur">{degreeLabel}</span><span className="rounded-full bg-white/18 px-3 py-1 font-mono-ui text-[0.65rem] uppercase tracking-[.15em] backdrop-blur">Verified profile</span></div><h1 className="font-editorial max-w-3xl text-4xl font-semibold leading-none tracking-tight sm:text-5xl">{program.universityName}</h1><p className="mt-3 text-base text-white/85">{program.programName}</p></div>
      </div>
      <div className="grid gap-4 p-5 sm:grid-cols-[1fr_auto] sm:items-center sm:p-7"><div className="flex flex-wrap gap-x-5 gap-y-2 text-sm text-slate-600"><span className="flex items-center gap-1.5"><MapPin className="h-4 w-4 text-violet-600" />{program.city}, {program.state}</span><span className="flex items-center gap-1.5"><Building2 className="h-4 w-4 text-violet-600" />{program.department}</span><span className="flex items-center gap-1.5"><BadgeCheck className="h-4 w-4 text-teal-600" />Checked {program.verifiedAt ? new Date(program.verifiedAt).toLocaleDateString() : "—"}</span></div><Button onClick={() => add.mutate({ programId: program.id })} className="rounded-xl bg-violet-700 hover:bg-violet-800"><BookmarkPlus className="mr-2 h-4 w-4" />Track application</Button></div>
    </section>

    <div className="grid gap-5 xl:grid-cols-[1.42fr_.58fr]">
      <div className="space-y-5">
        <section className="surface p-5 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="section-kicker">Admission snapshot</p><h2 className="mt-2 text-2xl font-extrabold tracking-tight">What to check before you apply.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">Only source-backed facts appear here. If a fee, test policy, or rate is absent, the record does not make a claim about it.</p></div><a href={program.applicationUrl ?? program.officialUrl} target="_blank" rel="noreferrer" className="inline-flex h-10 items-center gap-2 rounded-xl bg-teal-600 px-4 text-sm font-bold text-white transition hover:bg-teal-700 active:scale-95">Official application <ExternalLink className="h-4 w-4" /></a></div>
          {facts.length ? <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{facts.map(fact => <AdmissionFact key={fact.label} {...fact} />)}</div> : <div className="mt-6 rounded-2xl bg-slate-50 p-4 text-sm text-slate-600">Open the official program page for current admissions requirements and deadlines.</div>}
        </section>
        <section className="surface overflow-hidden"><details><summary className="cursor-pointer list-none p-5 sm:p-7"><div className="flex items-center justify-between gap-3"><div><p className="section-kicker">Verified program context</p><h2 className="mt-2 text-xl font-extrabold tracking-tight">Research fit, requirements, and details</h2><p className="mt-2 text-sm text-slate-600">Open only when you want the fuller verified context.</p></div><span className="rounded-full bg-violet-50 px-3 py-1.5 text-xs font-bold text-violet-800">Expand</span></div></summary><div className="border-t border-slate-100 p-5 pt-0 sm:p-7 sm:pt-0"><p className="pt-6 leading-7 text-slate-700">{program.description ?? "See the official program page for the current description."}</p><div className="mt-6 grid gap-6 md:grid-cols-2"><div><h3 className="text-sm font-extrabold uppercase tracking-wide text-slate-800">Research areas</h3><div className="mt-3 flex flex-wrap gap-2">{(program.facultyResearchAreas ?? []).map(item => <span key={item} className="rounded-full bg-violet-50 px-3 py-1.5 text-xs font-semibold text-violet-800">{item}</span>)}</div></div><div><h3 className="text-sm font-extrabold uppercase tracking-wide text-slate-800">Curriculum highlights</h3><ul className="mt-3 space-y-2">{(program.curriculumHighlights ?? []).map(item => <li key={item} className="flex gap-2 text-sm text-slate-600"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-teal-600" />{item}</li>)}</ul></div></div>{requirements.length ? <div className="mt-6 rounded-2xl border border-teal-100 bg-teal-50/55 p-5"><h3 className="text-sm font-extrabold uppercase tracking-wide text-teal-950">Published application requirements</h3><ul className="mt-3 grid gap-2 sm:grid-cols-2">{requirements.map(item => <li key={item} className="flex gap-2 text-sm text-teal-900"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-teal-600" />{item}</li>)}</ul></div> : null}</div></details></section>
      </div>
      <aside className="space-y-5"><section className="surface p-5"><p className="section-kicker">Official links</p><div className="mt-4 space-y-2"><a href={program.officialUrl} target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-xl border border-slate-100 bg-slate-50 px-3.5 py-3 text-sm font-bold text-slate-700 transition hover:border-violet-200 hover:text-violet-800"><span className="flex items-center gap-2"><Landmark className="h-4 w-4" />Program page</span><ExternalLink className="h-4 w-4" /></a><a href={program.applicationUrl ?? program.officialUrl} target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-xl border border-slate-100 bg-slate-50 px-3.5 py-3 text-sm font-bold text-slate-700 transition hover:border-violet-200 hover:text-violet-800"><span className="flex items-center gap-2"><FileText className="h-4 w-4" />Application page</span><ExternalLink className="h-4 w-4" /></a></div></section><section className="rounded-3xl bg-violet-950 p-6 text-violet-50"><ShieldCheck className="h-5 w-5 text-teal-300" /><h2 className="mt-3 font-editorial text-2xl font-semibold">Source-first, not guess-first.</h2><p className="mt-2 text-sm leading-6 text-violet-200">Program facts come from reconciled university sources. External acceptance context appears only when its own label and link are available.</p></section></aside>
    </div>
  </div>;
}

function AdmissionFact({ label, value, sourceUrl, sourceLabel }: { label: string; value: string; sourceUrl?: string | null; sourceLabel?: string | null }) { return <div className="rounded-2xl border border-slate-100 bg-slate-50/70 p-4"><p className="font-mono-ui text-[0.6rem] uppercase tracking-[.14em] text-slate-500">{label}</p><p className="mt-2 text-sm font-extrabold leading-5 text-slate-900">{value}</p>{sourceUrl ? <a href={sourceUrl} target="_blank" rel="noreferrer" className="mt-2 inline-flex items-center gap-1 text-[0.62rem] font-bold uppercase tracking-wide text-violet-700 hover:text-violet-900">{sourceLabel ?? "Source"}<ExternalLink className="h-3 w-3" /></a> : null}</div>; }
