import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Archive, CalendarClock, ChevronRight, CirclePlus, ExternalLink, FileCheck2, Mail, PencilLine, UserRoundPlus } from "lucide-react";
import { toast } from "sonner";

const pipeline = ["researching", "applied", "interview", "offer", "accepted", "rejected"] as const;
const labels: Record<(typeof pipeline)[number], string> = { researching: "Researching", applied: "Applied", interview: "Interview", offer: "Offer", accepted: "Accepted", rejected: "Rejected" };

export default function Tracker() {
  const { data: items = [], isLoading } = trpc.tracker.applications.list.useQuery();
  const { data: legacyItems = [] } = trpc.tracker.legacy.list.useQuery();
  const utils = trpc.useUtils();
  const refresh = () => utils.tracker.applications.list.invalidate();
  const update = trpc.tracker.applications.update.useMutation({ onSuccess: refresh, onError: error => toast.error(error.message) });
  const toggleDoc = trpc.tracker.applications.toggleDocument.useMutation({ onSuccess: refresh, onError: error => toast.error(error.message) });
  const addLetter = trpc.tracker.applications.addRecommender.useMutation({ onSuccess: refresh, onError: error => toast.error(error.message) });
  const updateLetter = trpc.tracker.applications.updateRecommender.useMutation({ onSuccess: refresh, onError: error => toast.error(error.message) });

  if (isLoading) return <div className="content-frame py-20 text-center text-slate-500">Loading your applications…</div>;

  return <div className="content-frame page-enter space-y-6">
    <section className="surface flex flex-col justify-between gap-5 p-6 sm:flex-row sm:items-end sm:p-8"><div><p className="section-kicker">My Applications</p><h1 className="font-editorial mt-2 text-4xl font-semibold tracking-tight text-slate-950">One calm place for every moving part.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">Move each application through the exact pipeline, collect documents, track up to three letters, and keep your personal contacts and next steps beside the program.</p></div><div className="rounded-2xl bg-teal-50 px-5 py-4 text-sm text-teal-900"><span className="font-mono-ui text-[.62rem] uppercase tracking-[.16em]">Pipeline</span><p className="mt-1 font-bold">Researching → Applied → Interview → Offer → Accepted/Rejected</p></div></section>
    {legacyItems.length ? <details className="surface group overflow-hidden"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-amber-100 text-amber-800"><Archive className="h-5 w-5" /></span><div><p className="section-kicker">Private archive</p><h2 className="mt-1 text-base font-extrabold">{legacyItems.length} rows preserved from your uploaded tracker</h2></div></div><ChevronRight className="h-5 w-5 text-slate-400 transition-transform group-open:rotate-90" /></summary><div className="border-t border-slate-100 bg-amber-50/35 p-5 sm:p-6"><p className="max-w-3xl text-sm leading-6 text-slate-600">These are your original university, program, link, deadline, status, result, and note fields. They remain private and are intentionally not displayed as verified directory facts until an official-source record is reconciled.</p><div className="mt-5 grid gap-3 md:grid-cols-2">{legacyItems.map(record => <article key={record.id} className="rounded-2xl bg-white p-4 shadow-sm ring-1 ring-amber-100"><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold text-slate-900">{record.universityName}</h3><p className="mt-0.5 text-sm text-slate-600">{record.programName}</p></div>{record.legacyWebsite ? <a href={record.legacyWebsite} target="_blank" rel="noreferrer" className="rounded-lg p-2 text-amber-800 hover:bg-amber-100" aria-label={`Open legacy link for ${record.universityName}`}><ExternalLink className="h-4 w-4" /></a> : null}</div><div className="mt-3 flex flex-wrap gap-1.5 text-[.67rem] font-bold"><span className="rounded-full bg-slate-100 px-2 py-1 text-slate-600">Legacy: {record.sourceApplicationStatus}</span><span className="rounded-full bg-slate-100 px-2 py-1 text-slate-600">Result: {record.sourceResult}</span>{record.legacyDeadline ? <span className="rounded-full bg-amber-100 px-2 py-1 text-amber-900">Legacy deadline: {new Date(record.legacyDeadline).toLocaleDateString()}</span> : null}</div>{record.notes ? <p className="mt-3 whitespace-pre-wrap text-sm leading-5 text-slate-600">{record.notes}</p> : null}</article>)}</div></div></details> : null}
    {items.length ? <div className="space-y-4">{items.map((item, index) => {
      const complete = item.documents.filter(document => document.isComplete).length;
      const pct = item.documents.length ? Math.round((complete / item.documents.length) * 100) : 0;
      const reminderValue = item.application.reminderAt ? new Date(item.application.reminderAt).toISOString().slice(0, 10) : "";
      return <section key={item.application.id} className="surface stagger-item p-5 sm:p-6" style={{ animationDelay: `${Math.min(index * 45, 220)}ms` }}>
        <div className="flex flex-col gap-5 xl:flex-row xl:items-start xl:justify-between"><div><p className="section-kicker">{item.program.degreeType === "phd" ? "PhD" : "Master’s"} · {item.program.state}</p><h2 className="mt-1 text-xl font-extrabold tracking-tight">{item.program.universityName}</h2><p className="mt-1 text-sm text-slate-600">{item.program.programName}</p></div><div className="flex flex-wrap gap-1.5">{pipeline.map((status, position) => <button key={status} onClick={() => update.mutate({ applicationId: item.application.id, status })} className={`inline-flex items-center gap-1 rounded-full px-3 py-1.5 text-xs font-bold transition active:scale-95 ${item.application.status === status ? status === "rejected" ? "bg-rose-600 text-white" : "bg-violet-700 text-white" : "bg-slate-100 text-slate-500 hover:bg-violet-50 hover:text-violet-700"}`}>{position > 0 ? <ChevronRight className="h-3 w-3" /> : null}{labels[status]}</button>)}</div></div>
        <div className="mt-6 grid gap-5 xl:grid-cols-[.9fr_1.1fr_.8fr]">
          <div className="rounded-2xl bg-slate-50 p-4"><div className="flex items-center justify-between"><h3 className="text-sm font-extrabold">Documents</h3><span className="font-mono-ui text-xs font-medium text-violet-700">{pct}%</span></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-gradient-to-r from-violet-600 to-teal-400 transition-all" style={{ width: `${pct}%` }} /></div><div className="mt-4 space-y-3">{item.documents.map(document => <label key={document.id} className="flex cursor-pointer items-center gap-2 text-sm text-slate-600"><Checkbox checked={document.isComplete} onCheckedChange={value => toggleDoc.mutate({ documentId: document.id, isComplete: Boolean(value) })} /><span className={document.isComplete ? "text-slate-400 line-through" : ""}>{document.label}</span></label>)}</div></div>
          <div className="rounded-2xl bg-violet-50/65 p-4"><div className="flex items-center justify-between"><h3 className="text-sm font-extrabold">Letters of recommendation</h3><span className="font-mono-ui text-xs text-violet-700">{item.recommenders.length}/3</span></div><div className="mt-3 space-y-3">{item.recommenders.map(letter => <div key={letter.id} className="rounded-xl bg-white p-3"><Input defaultValue={letter.name ?? ""} onBlur={event => updateLetter.mutate({ recommenderId: letter.id, name: event.target.value })} className="h-8 border-0 bg-transparent px-0 text-sm font-semibold shadow-none focus-visible:ring-0" placeholder={`Recommender ${letter.slot} name`} /><div className="mt-1 flex items-center gap-2"><Mail className="h-3.5 w-3.5 text-slate-400" /><Input defaultValue={letter.email ?? ""} onBlur={event => updateLetter.mutate({ recommenderId: letter.id, email: event.target.value })} className="h-7 border-0 bg-transparent px-0 text-xs shadow-none focus-visible:ring-0" placeholder="email@university.edu" /><select defaultValue={letter.status} onChange={event => updateLetter.mutate({ recommenderId: letter.id, status: event.target.value as "not_requested" | "requested" | "received" })} className="rounded-md border-0 bg-slate-100 px-1.5 py-1 text-[.62rem] font-bold text-slate-600"><option value="not_requested">Not requested</option><option value="requested">Requested</option><option value="received">Received</option></select></div></div>)}</div>{item.recommenders.length < 3 ? <button onClick={() => addLetter.mutate({ applicationId: item.application.id })} className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-violet-700 hover:text-violet-900"><UserRoundPlus className="h-3.5 w-3.5" />Add letter</button> : null}</div>
          <div className="rounded-2xl bg-teal-50/60 p-4"><div className="flex items-center gap-2"><PencilLine className="h-4 w-4 text-teal-700" /><h3 className="text-sm font-extrabold">Notes, contacts & reminders</h3></div><div className="mt-3 grid gap-2"><Input defaultValue={item.application.primaryContactName ?? ""} onBlur={event => update.mutate({ applicationId: item.application.id, primaryContactName: event.target.value })} className="h-9 border-teal-100 bg-white text-sm" placeholder="Primary faculty or program contact" /><Input type="email" defaultValue={item.application.primaryContactEmail ?? ""} onBlur={event => update.mutate({ applicationId: item.application.id, primaryContactEmail: event.target.value })} className="h-9 border-teal-100 bg-white text-sm" placeholder="contact@university.edu" /><label className="flex items-center gap-2 text-xs font-bold text-teal-800"><CalendarClock className="h-3.5 w-3.5" />Next reminder <Input type="date" defaultValue={reminderValue} onBlur={event => update.mutate({ applicationId: item.application.id, reminderAt: event.target.value || null })} className="h-8 flex-1 border-teal-100 bg-white text-xs" /></label></div><Textarea defaultValue={item.application.notes ?? ""} onBlur={event => update.mutate({ applicationId: item.application.id, notes: event.target.value })} className="mt-3 min-h-24 resize-none border-teal-100 bg-white text-sm" placeholder="Faculty contact, interview notes, reminders, or useful observations…" /></div>
        </div>
      </section>;
    })}</div> : <div className="surface py-18 text-center"><FileCheck2 className="mx-auto h-9 w-9 text-violet-400" /><h2 className="mt-4 text-xl font-bold">Start by saving a verified program.</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-600">Your first saved program will arrive here with a clean document checklist and a private workspace for notes.</p><Button onClick={() => window.location.assign("/programs")} className="mt-5 rounded-xl bg-violet-700"><CirclePlus className="mr-2 h-4 w-4" />Explore programs</Button></div>}
  </div>;
}
